language: node_js
node_js:
  - 4
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install xclip xsel --no-install-recommends --yes
  - export DISPLAY=:99.0
  - "sh -e /etc/init.d/xvfb start"
